#ifndef LITTLE_ONE_GAME_SETTINGS_H
#define LITTLE_ONE_GAME_SETTINGS_H

#define LITTLE_ONE_TARGET_FPS 60
#define LITTLE_ONE_UNCAPPED_FPS 0

#define LITTLE_ONE_SHOW_FPS 1
#define LITTLE_ONE_LOG_FPS 1
#define LITTLE_ONE_SHOW_WIREFRAMES 1

#define LITTLE_ONE_DEBUG_INPUT 0
#define LITTLE_ONE_DEBUG_SMASH 0

#define LITTLE_ONE_GROUND_BOTTOM_MARGIN_PX 300.0f
#define LITTLE_ONE_WORLD_SCROLL_SPEED 300.0f

#define LITTLE_ONE_MOVEMENT_TOUCH_ZONE_RATIO 0.70f
#define LITTLE_ONE_MOVEMENT_DEADZONE_PX 24.0f

#endif
