// Generated by tools/pack_animations.py. Do not edit manually.
#include "animation_definition.h"

// Source: src/sprites/animations/idle.anim.json
static const AnimKey IDLE_OFFSET_Y_KEYS[] = {
    {0, 0, ANIM_EASE_LINEAR},
    {450, -5, ANIM_EASE_OUT},
    {900, 0, ANIM_EASE_IN},
};

static const AnimKey IDLE_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {450, 1020, ANIM_EASE_OUT},
    {900, 1000, ANIM_EASE_IN},
};

static const AnimKey IDLE_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {450, 980, ANIM_EASE_OUT},
    {900, 1000, ANIM_EASE_IN},
};

static const AnimTrack IDLE_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = IDLE_OFFSET_Y_KEYS,
        .key_count = sizeof(IDLE_OFFSET_Y_KEYS) / sizeof(IDLE_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = IDLE_SCALE_X_KEYS,
        .key_count = sizeof(IDLE_SCALE_X_KEYS) / sizeof(IDLE_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = IDLE_SCALE_Y_KEYS,
        .key_count = sizeof(IDLE_SCALE_Y_KEYS) / sizeof(IDLE_SCALE_Y_KEYS[0]),
    },
};

// Source: src/sprites/animations/walk.anim.json
static const AnimKey WALK_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {150, 930, ANIM_EASE_OUT},
    {300, 1080, ANIM_EASE_IN_OUT},
    {450, 930, ANIM_EASE_OUT},
    {600, 1000, ANIM_EASE_IN},
};

static const AnimKey WALK_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {150, 1080, ANIM_EASE_OUT},
    {300, 930, ANIM_EASE_IN_OUT},
    {450, 1080, ANIM_EASE_OUT},
    {600, 1000, ANIM_EASE_IN},
};

static const AnimTrack WALK_TRACKS[] = {
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = WALK_SCALE_X_KEYS,
        .key_count = sizeof(WALK_SCALE_X_KEYS) / sizeof(WALK_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = WALK_SCALE_Y_KEYS,
        .key_count = sizeof(WALK_SCALE_Y_KEYS) / sizeof(WALK_SCALE_Y_KEYS[0]),
    },
};

// Source: src/sprites/animations/jump.anim.json
static const AnimKey JUMP_OFFSET_Y_KEYS[] = {
    {0, 0, ANIM_EASE_LINEAR},
    {80, -3, ANIM_EASE_OUT},
    {220, -2, ANIM_EASE_IN_OUT},
};

static const AnimKey JUMP_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {80, 920, ANIM_EASE_OUT},
    {220, 940, ANIM_EASE_IN_OUT},
};

static const AnimKey JUMP_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {80, 1120, ANIM_EASE_OUT},
    {220, 1080, ANIM_EASE_IN_OUT},
};

static const AnimTrack JUMP_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = JUMP_OFFSET_Y_KEYS,
        .key_count = sizeof(JUMP_OFFSET_Y_KEYS) / sizeof(JUMP_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = JUMP_SCALE_X_KEYS,
        .key_count = sizeof(JUMP_SCALE_X_KEYS) / sizeof(JUMP_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = JUMP_SCALE_Y_KEYS,
        .key_count = sizeof(JUMP_SCALE_Y_KEYS) / sizeof(JUMP_SCALE_Y_KEYS[0]),
    },
};

// Source: src/sprites/animations/fall.anim.json
static const AnimKey FALL_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {160, 1060, ANIM_EASE_OUT},
};

static const AnimKey FALL_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {160, 940, ANIM_EASE_OUT},
};

static const AnimTrack FALL_TRACKS[] = {
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = FALL_SCALE_X_KEYS,
        .key_count = sizeof(FALL_SCALE_X_KEYS) / sizeof(FALL_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = FALL_SCALE_Y_KEYS,
        .key_count = sizeof(FALL_SCALE_Y_KEYS) / sizeof(FALL_SCALE_Y_KEYS[0]),
    },
};

// Source: src/sprites/animations/smash.anim.json
static const AnimKey SMASH_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {80, 1150, ANIM_EASE_OUT},
    {250, 1100, ANIM_EASE_IN},
};

static const AnimKey SMASH_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {80, 850, ANIM_EASE_OUT},
    {250, 900, ANIM_EASE_IN},
};

static const AnimKey SMASH_ROTATION_KEYS[] = {
    {0, 0, ANIM_EASE_LINEAR},
    {80, 350, ANIM_EASE_OUT},
    {250, 350, ANIM_EASE_LINEAR},
};

static const AnimTrack SMASH_TRACKS[] = {
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = SMASH_SCALE_X_KEYS,
        .key_count = sizeof(SMASH_SCALE_X_KEYS) / sizeof(SMASH_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = SMASH_SCALE_Y_KEYS,
        .key_count = sizeof(SMASH_SCALE_Y_KEYS) / sizeof(SMASH_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = SMASH_ROTATION_KEYS,
        .key_count = sizeof(SMASH_ROTATION_KEYS) / sizeof(SMASH_ROTATION_KEYS[0]),
    },
};

// Source: src/sprites/animations/land.anim.json
static const AnimKey LAND_OFFSET_Y_KEYS[] = {
    {0, 0, ANIM_EASE_LINEAR},
    {60, 4, ANIM_EASE_OUT},
    {130, -2, ANIM_EASE_IN_OUT},
    {220, 0, ANIM_EASE_IN},
};

static const AnimKey LAND_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {60, 1250, ANIM_EASE_OUT},
    {130, 950, ANIM_EASE_IN_OUT},
    {220, 1000, ANIM_EASE_IN},
};

static const AnimKey LAND_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {60, 750, ANIM_EASE_OUT},
    {130, 1100, ANIM_EASE_IN_OUT},
    {220, 1000, ANIM_EASE_IN},
};

static const AnimTrack LAND_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = LAND_OFFSET_Y_KEYS,
        .key_count = sizeof(LAND_OFFSET_Y_KEYS) / sizeof(LAND_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = LAND_SCALE_X_KEYS,
        .key_count = sizeof(LAND_SCALE_X_KEYS) / sizeof(LAND_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = LAND_SCALE_Y_KEYS,
        .key_count = sizeof(LAND_SCALE_Y_KEYS) / sizeof(LAND_SCALE_Y_KEYS[0]),
    },
};

// Source: src/sprites/animations/damage.anim.json
static const AnimKey DAMAGE_OFFSET_X_KEYS[] = {
    {0, 0, ANIM_EASE_LINEAR},
    {40, -4, ANIM_EASE_STEP},
    {80, 4, ANIM_EASE_STEP},
    {120, -3, ANIM_EASE_STEP},
    {170, 2, ANIM_EASE_STEP},
    {240, 0, ANIM_EASE_OUT},
};

static const AnimKey DAMAGE_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {70, 1150, ANIM_EASE_OUT},
    {240, 1000, ANIM_EASE_IN},
};

static const AnimKey DAMAGE_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {70, 850, ANIM_EASE_OUT},
    {240, 1000, ANIM_EASE_IN},
};

static const AnimTrack DAMAGE_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_X,
        .keys = DAMAGE_OFFSET_X_KEYS,
        .key_count = sizeof(DAMAGE_OFFSET_X_KEYS) / sizeof(DAMAGE_OFFSET_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = DAMAGE_SCALE_X_KEYS,
        .key_count = sizeof(DAMAGE_SCALE_X_KEYS) / sizeof(DAMAGE_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = DAMAGE_SCALE_Y_KEYS,
        .key_count = sizeof(DAMAGE_SCALE_Y_KEYS) / sizeof(DAMAGE_SCALE_Y_KEYS[0]),
    },
};

// Source: src/sprites/animations/death.anim.json
static const AnimKey DEATH_OFFSET_Y_KEYS[] = {
    {0, 0, ANIM_EASE_LINEAR},
    {150, 8, ANIM_EASE_OUT},
    {500, 12, ANIM_EASE_OUT},
};

static const AnimKey DEATH_SCALE_X_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {150, 1300, ANIM_EASE_OUT},
    {500, 1400, ANIM_EASE_OUT},
};

static const AnimKey DEATH_SCALE_Y_KEYS[] = {
    {0, 1000, ANIM_EASE_LINEAR},
    {150, 450, ANIM_EASE_OUT},
    {500, 250, ANIM_EASE_OUT},
};

static const AnimKey DEATH_ALPHA_KEYS[] = {
    {0, 255, ANIM_EASE_LINEAR},
    {350, 255, ANIM_EASE_LINEAR},
    {500, 0, ANIM_EASE_OUT},
};

static const AnimTrack DEATH_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = DEATH_OFFSET_Y_KEYS,
        .key_count = sizeof(DEATH_OFFSET_Y_KEYS) / sizeof(DEATH_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = DEATH_SCALE_X_KEYS,
        .key_count = sizeof(DEATH_SCALE_X_KEYS) / sizeof(DEATH_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = DEATH_SCALE_Y_KEYS,
        .key_count = sizeof(DEATH_SCALE_Y_KEYS) / sizeof(DEATH_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ALPHA,
        .keys = DEATH_ALPHA_KEYS,
        .key_count = sizeof(DEATH_ALPHA_KEYS) / sizeof(DEATH_ALPHA_KEYS[0]),
    },
};

const AnimationClip ANIMATION_CLIPS[] = {
    {
        .id = "idle",
        .duration_ms = 900,
        .loop = true,
        .tracks = IDLE_TRACKS,
        .track_count = sizeof(IDLE_TRACKS) / sizeof(IDLE_TRACKS[0]),
    },
    {
        .id = "walk",
        .duration_ms = 600,
        .loop = true,
        .tracks = WALK_TRACKS,
        .track_count = sizeof(WALK_TRACKS) / sizeof(WALK_TRACKS[0]),
    },
    {
        .id = "jump",
        .duration_ms = 220,
        .loop = false,
        .tracks = JUMP_TRACKS,
        .track_count = sizeof(JUMP_TRACKS) / sizeof(JUMP_TRACKS[0]),
    },
    {
        .id = "fall",
        .duration_ms = 160,
        .loop = false,
        .tracks = FALL_TRACKS,
        .track_count = sizeof(FALL_TRACKS) / sizeof(FALL_TRACKS[0]),
    },
    {
        .id = "smash",
        .duration_ms = 250,
        .loop = false,
        .tracks = SMASH_TRACKS,
        .track_count = sizeof(SMASH_TRACKS) / sizeof(SMASH_TRACKS[0]),
    },
    {
        .id = "land",
        .duration_ms = 220,
        .loop = false,
        .tracks = LAND_TRACKS,
        .track_count = sizeof(LAND_TRACKS) / sizeof(LAND_TRACKS[0]),
    },
    {
        .id = "damage",
        .duration_ms = 240,
        .loop = false,
        .tracks = DAMAGE_TRACKS,
        .track_count = sizeof(DAMAGE_TRACKS) / sizeof(DAMAGE_TRACKS[0]),
    },
    {
        .id = "death",
        .duration_ms = 500,
        .loop = false,
        .tracks = DEATH_TRACKS,
        .track_count = sizeof(DEATH_TRACKS) / sizeof(DEATH_TRACKS[0]),
    },
};

const uint8_t ANIMATION_CLIP_COUNT = sizeof(ANIMATION_CLIPS) / sizeof(ANIMATION_CLIPS[0]);
