// Generated by tools/pack_animations.py. Do not edit manually.
#include "animation_definition.h"

// Source: src/assets/animations/boar_walk.anim.json
static const AnimKey BOAR_WALK_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 125, 2, ANIM_EASE_OUT },
    { 250, 0, ANIM_EASE_IN_OUT },
    { 375, 2, ANIM_EASE_OUT },
    { 500, 0, ANIM_EASE_IN },
};

static const AnimKey BOAR_WALK_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 125, 1080, ANIM_EASE_OUT },
    { 250, 970, ANIM_EASE_IN_OUT },
    { 375, 1080, ANIM_EASE_OUT },
    { 500, 1000, ANIM_EASE_IN },
};

static const AnimKey BOAR_WALK_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 125, 930, ANIM_EASE_OUT },
    { 250, 1040, ANIM_EASE_IN_OUT },
    { 375, 930, ANIM_EASE_OUT },
    { 500, 1000, ANIM_EASE_IN },
};

static const AnimTrack BOAR_WALK_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = BOAR_WALK_OFFSET_Y_KEYS,
        .key_count = sizeof(BOAR_WALK_OFFSET_Y_KEYS) / sizeof(BOAR_WALK_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = BOAR_WALK_SCALE_X_KEYS,
        .key_count = sizeof(BOAR_WALK_SCALE_X_KEYS) / sizeof(BOAR_WALK_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = BOAR_WALK_SCALE_Y_KEYS,
        .key_count = sizeof(BOAR_WALK_SCALE_Y_KEYS) / sizeof(BOAR_WALK_SCALE_Y_KEYS[0]),
    },
};

// Source: src/assets/animations/damage.anim.json
static const AnimKey DAMAGE_OFFSET_X_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 30, -5, ANIM_EASE_STEP },
    { 60, 5, ANIM_EASE_STEP },
    { 90, -4, ANIM_EASE_STEP },
    { 125, 3, ANIM_EASE_STEP },
    { 170, -2, ANIM_EASE_STEP },
    { 230, 0, ANIM_EASE_OUT },
};

static const AnimKey DAMAGE_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 55, 1180, ANIM_EASE_OUT },
    { 230, 1000, ANIM_EASE_IN },
};

static const AnimKey DAMAGE_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 55, 820, ANIM_EASE_OUT },
    { 230, 1000, ANIM_EASE_IN },
};

static const AnimTrack DAMAGE_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_X,
        .keys = DAMAGE_OFFSET_X_KEYS,
        .key_count = sizeof(DAMAGE_OFFSET_X_KEYS) / sizeof(DAMAGE_OFFSET_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = DAMAGE_SCALE_X_KEYS,
        .key_count = sizeof(DAMAGE_SCALE_X_KEYS) / sizeof(DAMAGE_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = DAMAGE_SCALE_Y_KEYS,
        .key_count = sizeof(DAMAGE_SCALE_Y_KEYS) / sizeof(DAMAGE_SCALE_Y_KEYS[0]),
    },
};

// Source: src/assets/animations/death.anim.json
static const AnimKey DEATH_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 80, -6, ANIM_EASE_OUT },
    { 180, 12, ANIM_EASE_IN },
    { 520, 16, ANIM_EASE_OUT },
};

static const AnimKey DEATH_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 80, 850, ANIM_EASE_OUT },
    { 180, 1450, ANIM_EASE_OUT },
    { 520, 1500, ANIM_EASE_OUT },
};

static const AnimKey DEATH_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 80, 1180, ANIM_EASE_OUT },
    { 180, 360, ANIM_EASE_OUT },
    { 520, 220, ANIM_EASE_OUT },
};

static const AnimKey DEATH_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, 180, ANIM_EASE_OUT },
    { 520, 180, ANIM_EASE_LINEAR },
};

static const AnimKey DEATH_ALPHA_KEYS[] = {
    { 0, 255, ANIM_EASE_LINEAR },
    { 320, 255, ANIM_EASE_LINEAR },
    { 520, 0, ANIM_EASE_OUT },
};

static const AnimTrack DEATH_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = DEATH_OFFSET_Y_KEYS,
        .key_count = sizeof(DEATH_OFFSET_Y_KEYS) / sizeof(DEATH_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = DEATH_SCALE_X_KEYS,
        .key_count = sizeof(DEATH_SCALE_X_KEYS) / sizeof(DEATH_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = DEATH_SCALE_Y_KEYS,
        .key_count = sizeof(DEATH_SCALE_Y_KEYS) / sizeof(DEATH_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = DEATH_ROTATION_KEYS,
        .key_count = sizeof(DEATH_ROTATION_KEYS) / sizeof(DEATH_ROTATION_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ALPHA,
        .keys = DEATH_ALPHA_KEYS,
        .key_count = sizeof(DEATH_ALPHA_KEYS) / sizeof(DEATH_ALPHA_KEYS[0]),
    },
};

// Source: src/assets/animations/fall.anim.json
static const AnimKey FALL_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, 2, ANIM_EASE_OUT },
};

static const AnimKey FALL_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 180, 1080, ANIM_EASE_OUT },
};

static const AnimKey FALL_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 180, 920, ANIM_EASE_OUT },
};

static const AnimKey FALL_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, 100, ANIM_EASE_OUT },
};

static const AnimTrack FALL_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = FALL_OFFSET_Y_KEYS,
        .key_count = sizeof(FALL_OFFSET_Y_KEYS) / sizeof(FALL_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = FALL_SCALE_X_KEYS,
        .key_count = sizeof(FALL_SCALE_X_KEYS) / sizeof(FALL_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = FALL_SCALE_Y_KEYS,
        .key_count = sizeof(FALL_SCALE_Y_KEYS) / sizeof(FALL_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = FALL_ROTATION_KEYS,
        .key_count = sizeof(FALL_ROTATION_KEYS) / sizeof(FALL_ROTATION_KEYS[0]),
    },
};

// Source: src/assets/animations/fly.anim.json
static const AnimKey FLY_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 160, -6, ANIM_EASE_OUT },
    { 320, 0, ANIM_EASE_IN_OUT },
    { 480, 5, ANIM_EASE_OUT },
    { 640, 0, ANIM_EASE_IN },
};

static const AnimKey FLY_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 160, 880, ANIM_EASE_OUT },
    { 320, 1000, ANIM_EASE_IN_OUT },
    { 480, 1080, ANIM_EASE_OUT },
    { 640, 1000, ANIM_EASE_IN },
};

static const AnimKey FLY_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 160, -80, ANIM_EASE_OUT },
    { 320, 0, ANIM_EASE_IN_OUT },
    { 480, 80, ANIM_EASE_OUT },
    { 640, 0, ANIM_EASE_IN },
};

static const AnimTrack FLY_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = FLY_OFFSET_Y_KEYS,
        .key_count = sizeof(FLY_OFFSET_Y_KEYS) / sizeof(FLY_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = FLY_SCALE_Y_KEYS,
        .key_count = sizeof(FLY_SCALE_Y_KEYS) / sizeof(FLY_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = FLY_ROTATION_KEYS,
        .key_count = sizeof(FLY_ROTATION_KEYS) / sizeof(FLY_ROTATION_KEYS[0]),
    },
};

// Source: src/assets/animations/flying_death.anim.json
static const AnimKey FLYING_DEATH_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, 12, ANIM_EASE_IN },
    { 520, 34, ANIM_EASE_IN },
};

static const AnimKey FLYING_DEATH_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, 900, ANIM_EASE_IN },
    { 520, 2200, ANIM_EASE_IN },
};

static const AnimKey FLYING_DEATH_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 520, 700, ANIM_EASE_IN },
};

static const AnimKey FLYING_DEATH_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 520, 700, ANIM_EASE_IN },
};

static const AnimKey FLYING_DEATH_ALPHA_KEYS[] = {
    { 0, 255, ANIM_EASE_LINEAR },
    { 360, 255, ANIM_EASE_LINEAR },
    { 520, 0, ANIM_EASE_OUT },
};

static const AnimTrack FLYING_DEATH_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = FLYING_DEATH_OFFSET_Y_KEYS,
        .key_count = sizeof(FLYING_DEATH_OFFSET_Y_KEYS) / sizeof(FLYING_DEATH_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = FLYING_DEATH_ROTATION_KEYS,
        .key_count = sizeof(FLYING_DEATH_ROTATION_KEYS) / sizeof(FLYING_DEATH_ROTATION_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = FLYING_DEATH_SCALE_X_KEYS,
        .key_count = sizeof(FLYING_DEATH_SCALE_X_KEYS) / sizeof(FLYING_DEATH_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = FLYING_DEATH_SCALE_Y_KEYS,
        .key_count = sizeof(FLYING_DEATH_SCALE_Y_KEYS) / sizeof(FLYING_DEATH_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ALPHA,
        .keys = FLYING_DEATH_ALPHA_KEYS,
        .key_count = sizeof(FLYING_DEATH_ALPHA_KEYS) / sizeof(FLYING_DEATH_ALPHA_KEYS[0]),
    },
};

// Source: src/assets/animations/idle.anim.json
static const AnimKey IDLE_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 360, -3, ANIM_EASE_OUT },
    { 720, 0, ANIM_EASE_IN },
};

static const AnimKey IDLE_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 360, 1015, ANIM_EASE_OUT },
    { 720, 1000, ANIM_EASE_IN },
};

static const AnimKey IDLE_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 360, 985, ANIM_EASE_OUT },
    { 720, 1000, ANIM_EASE_IN },
};

static const AnimTrack IDLE_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = IDLE_OFFSET_Y_KEYS,
        .key_count = sizeof(IDLE_OFFSET_Y_KEYS) / sizeof(IDLE_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = IDLE_SCALE_X_KEYS,
        .key_count = sizeof(IDLE_SCALE_X_KEYS) / sizeof(IDLE_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = IDLE_SCALE_Y_KEYS,
        .key_count = sizeof(IDLE_SCALE_Y_KEYS) / sizeof(IDLE_SCALE_Y_KEYS[0]),
    },
};

// Source: src/assets/animations/jump.anim.json
static const AnimKey JUMP_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 60, -5, ANIM_EASE_OUT },
    { 180, -2, ANIM_EASE_IN_OUT },
    { 280, 0, ANIM_EASE_IN },
};

static const AnimKey JUMP_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 60, 870, ANIM_EASE_OUT },
    { 180, 930, ANIM_EASE_IN_OUT },
    { 280, 1000, ANIM_EASE_IN },
};

static const AnimKey JUMP_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 60, 1220, ANIM_EASE_OUT },
    { 180, 1080, ANIM_EASE_IN_OUT },
    { 280, 1000, ANIM_EASE_IN },
};

static const AnimKey JUMP_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 90, -120, ANIM_EASE_OUT },
    { 280, 0, ANIM_EASE_IN },
};

static const AnimTrack JUMP_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = JUMP_OFFSET_Y_KEYS,
        .key_count = sizeof(JUMP_OFFSET_Y_KEYS) / sizeof(JUMP_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = JUMP_SCALE_X_KEYS,
        .key_count = sizeof(JUMP_SCALE_X_KEYS) / sizeof(JUMP_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = JUMP_SCALE_Y_KEYS,
        .key_count = sizeof(JUMP_SCALE_Y_KEYS) / sizeof(JUMP_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = JUMP_ROTATION_KEYS,
        .key_count = sizeof(JUMP_ROTATION_KEYS) / sizeof(JUMP_ROTATION_KEYS[0]),
    },
};

// Source: src/assets/animations/land.anim.json
static const AnimKey LAND_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 45, 7, ANIM_EASE_OUT },
    { 110, -3, ANIM_EASE_IN_OUT },
    { 190, 0, ANIM_EASE_IN },
};

static const AnimKey LAND_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 45, 1320, ANIM_EASE_OUT },
    { 110, 900, ANIM_EASE_IN_OUT },
    { 190, 1000, ANIM_EASE_IN },
};

static const AnimKey LAND_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 45, 680, ANIM_EASE_OUT },
    { 110, 1160, ANIM_EASE_IN_OUT },
    { 190, 1000, ANIM_EASE_IN },
};

static const AnimTrack LAND_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = LAND_OFFSET_Y_KEYS,
        .key_count = sizeof(LAND_OFFSET_Y_KEYS) / sizeof(LAND_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = LAND_SCALE_X_KEYS,
        .key_count = sizeof(LAND_SCALE_X_KEYS) / sizeof(LAND_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = LAND_SCALE_Y_KEYS,
        .key_count = sizeof(LAND_SCALE_Y_KEYS) / sizeof(LAND_SCALE_Y_KEYS[0]),
    },
};

// Source: src/assets/animations/obstacle_break.anim.json
static const AnimKey OBSTACLE_BREAK_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 80, -5, ANIM_EASE_OUT },
    { 260, 10, ANIM_EASE_IN },
};

static const AnimKey OBSTACLE_BREAK_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 80, 1180, ANIM_EASE_OUT },
    { 260, 1550, ANIM_EASE_OUT },
};

static const AnimKey OBSTACLE_BREAK_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 80, 820, ANIM_EASE_OUT },
    { 260, 300, ANIM_EASE_IN },
};

static const AnimKey OBSTACLE_BREAK_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 260, -420, ANIM_EASE_OUT },
};

static const AnimKey OBSTACLE_BREAK_ALPHA_KEYS[] = {
    { 0, 255, ANIM_EASE_LINEAR },
    { 180, 255, ANIM_EASE_LINEAR },
    { 260, 0, ANIM_EASE_OUT },
};

static const AnimTrack OBSTACLE_BREAK_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = OBSTACLE_BREAK_OFFSET_Y_KEYS,
        .key_count = sizeof(OBSTACLE_BREAK_OFFSET_Y_KEYS) / sizeof(OBSTACLE_BREAK_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = OBSTACLE_BREAK_SCALE_X_KEYS,
        .key_count = sizeof(OBSTACLE_BREAK_SCALE_X_KEYS) / sizeof(OBSTACLE_BREAK_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = OBSTACLE_BREAK_SCALE_Y_KEYS,
        .key_count = sizeof(OBSTACLE_BREAK_SCALE_Y_KEYS) / sizeof(OBSTACLE_BREAK_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = OBSTACLE_BREAK_ROTATION_KEYS,
        .key_count = sizeof(OBSTACLE_BREAK_ROTATION_KEYS) / sizeof(OBSTACLE_BREAK_ROTATION_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ALPHA,
        .keys = OBSTACLE_BREAK_ALPHA_KEYS,
        .key_count = sizeof(OBSTACLE_BREAK_ALPHA_KEYS) / sizeof(OBSTACLE_BREAK_ALPHA_KEYS[0]),
    },
};

// Source: src/assets/animations/ork_walk.anim.json
static const AnimKey ORK_WALK_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, -3, ANIM_EASE_OUT },
    { 360, 1, ANIM_EASE_IN_OUT },
    { 540, -2, ANIM_EASE_OUT },
    { 720, 0, ANIM_EASE_IN },
};

static const AnimKey ORK_WALK_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 180, 960, ANIM_EASE_OUT },
    { 360, 1060, ANIM_EASE_IN_OUT },
    { 540, 970, ANIM_EASE_OUT },
    { 720, 1000, ANIM_EASE_IN },
};

static const AnimKey ORK_WALK_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 180, 1070, ANIM_EASE_OUT },
    { 360, 930, ANIM_EASE_IN_OUT },
    { 540, 1060, ANIM_EASE_OUT },
    { 720, 1000, ANIM_EASE_IN },
};

static const AnimKey ORK_WALK_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, -60, ANIM_EASE_OUT },
    { 360, 40, ANIM_EASE_IN_OUT },
    { 540, -40, ANIM_EASE_OUT },
    { 720, 0, ANIM_EASE_IN },
};

static const AnimTrack ORK_WALK_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = ORK_WALK_OFFSET_Y_KEYS,
        .key_count = sizeof(ORK_WALK_OFFSET_Y_KEYS) / sizeof(ORK_WALK_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = ORK_WALK_SCALE_X_KEYS,
        .key_count = sizeof(ORK_WALK_SCALE_X_KEYS) / sizeof(ORK_WALK_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = ORK_WALK_SCALE_Y_KEYS,
        .key_count = sizeof(ORK_WALK_SCALE_Y_KEYS) / sizeof(ORK_WALK_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = ORK_WALK_ROTATION_KEYS,
        .key_count = sizeof(ORK_WALK_ROTATION_KEYS) / sizeof(ORK_WALK_ROTATION_KEYS[0]),
    },
};

// Source: src/assets/animations/predator_idle.anim.json
static const AnimKey PREDATOR_IDLE_OFFSET_X_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 220, -2, ANIM_EASE_IN },
    { 420, -5, ANIM_EASE_IN_OUT },
    { 540, 12, ANIM_EASE_OUT },
    { 620, 7, ANIM_EASE_IN_OUT },
    { 760, -3, ANIM_EASE_OUT },
    { 960, 0, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_IDLE_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 220, 2, ANIM_EASE_IN },
    { 420, 4, ANIM_EASE_IN_OUT },
    { 540, -5, ANIM_EASE_OUT },
    { 620, -2, ANIM_EASE_IN_OUT },
    { 760, 1, ANIM_EASE_OUT },
    { 960, 0, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_IDLE_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 220, -18, ANIM_EASE_IN },
    { 420, -34, ANIM_EASE_IN_OUT },
    { 540, 68, ANIM_EASE_OUT },
    { 620, 42, ANIM_EASE_IN_OUT },
    { 760, -16, ANIM_EASE_OUT },
    { 960, 0, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_IDLE_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 220, 1040, ANIM_EASE_IN },
    { 420, 1080, ANIM_EASE_IN_OUT },
    { 540, 900, ANIM_EASE_OUT },
    { 620, 960, ANIM_EASE_IN_OUT },
    { 760, 1040, ANIM_EASE_OUT },
    { 960, 1000, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_IDLE_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 220, 960, ANIM_EASE_IN },
    { 420, 930, ANIM_EASE_IN_OUT },
    { 540, 1160, ANIM_EASE_OUT },
    { 620, 1080, ANIM_EASE_IN_OUT },
    { 760, 960, ANIM_EASE_OUT },
    { 960, 1000, ANIM_EASE_IN },
};

static const AnimTrack PREDATOR_IDLE_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_X,
        .keys = PREDATOR_IDLE_OFFSET_X_KEYS,
        .key_count = sizeof(PREDATOR_IDLE_OFFSET_X_KEYS) / sizeof(PREDATOR_IDLE_OFFSET_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = PREDATOR_IDLE_OFFSET_Y_KEYS,
        .key_count = sizeof(PREDATOR_IDLE_OFFSET_Y_KEYS) / sizeof(PREDATOR_IDLE_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = PREDATOR_IDLE_ROTATION_KEYS,
        .key_count = sizeof(PREDATOR_IDLE_ROTATION_KEYS) / sizeof(PREDATOR_IDLE_ROTATION_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = PREDATOR_IDLE_SCALE_X_KEYS,
        .key_count = sizeof(PREDATOR_IDLE_SCALE_X_KEYS) / sizeof(PREDATOR_IDLE_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = PREDATOR_IDLE_SCALE_Y_KEYS,
        .key_count = sizeof(PREDATOR_IDLE_SCALE_Y_KEYS) / sizeof(PREDATOR_IDLE_SCALE_Y_KEYS[0]),
    },
};

// Source: src/assets/animations/predator_snap_idle.anim.json
static const AnimKey PREDATOR_SNAP_IDLE_OFFSET_X_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, -4, ANIM_EASE_IN },
    { 300, 16, ANIM_EASE_OUT },
    { 360, 9, ANIM_EASE_LINEAR },
    { 460, -5, ANIM_EASE_OUT },
    { 720, 0, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_SNAP_IDLE_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, 3, ANIM_EASE_IN },
    { 300, -7, ANIM_EASE_OUT },
    { 360, -3, ANIM_EASE_LINEAR },
    { 460, 2, ANIM_EASE_OUT },
    { 720, 0, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_SNAP_IDLE_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 180, -42, ANIM_EASE_IN },
    { 300, 92, ANIM_EASE_OUT },
    { 360, 55, ANIM_EASE_LINEAR },
    { 460, -24, ANIM_EASE_OUT },
    { 720, 0, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_SNAP_IDLE_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 180, 1100, ANIM_EASE_IN },
    { 300, 840, ANIM_EASE_OUT },
    { 360, 920, ANIM_EASE_LINEAR },
    { 460, 1080, ANIM_EASE_OUT },
    { 720, 1000, ANIM_EASE_IN },
};

static const AnimKey PREDATOR_SNAP_IDLE_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 180, 900, ANIM_EASE_IN },
    { 300, 1240, ANIM_EASE_OUT },
    { 360, 1120, ANIM_EASE_LINEAR },
    { 460, 930, ANIM_EASE_OUT },
    { 720, 1000, ANIM_EASE_IN },
};

static const AnimTrack PREDATOR_SNAP_IDLE_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_X,
        .keys = PREDATOR_SNAP_IDLE_OFFSET_X_KEYS,
        .key_count = sizeof(PREDATOR_SNAP_IDLE_OFFSET_X_KEYS) / sizeof(PREDATOR_SNAP_IDLE_OFFSET_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = PREDATOR_SNAP_IDLE_OFFSET_Y_KEYS,
        .key_count = sizeof(PREDATOR_SNAP_IDLE_OFFSET_Y_KEYS) / sizeof(PREDATOR_SNAP_IDLE_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = PREDATOR_SNAP_IDLE_ROTATION_KEYS,
        .key_count = sizeof(PREDATOR_SNAP_IDLE_ROTATION_KEYS) / sizeof(PREDATOR_SNAP_IDLE_ROTATION_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = PREDATOR_SNAP_IDLE_SCALE_X_KEYS,
        .key_count = sizeof(PREDATOR_SNAP_IDLE_SCALE_X_KEYS) / sizeof(PREDATOR_SNAP_IDLE_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = PREDATOR_SNAP_IDLE_SCALE_Y_KEYS,
        .key_count = sizeof(PREDATOR_SNAP_IDLE_SCALE_Y_KEYS) / sizeof(PREDATOR_SNAP_IDLE_SCALE_Y_KEYS[0]),
    },
};

// Source: src/assets/animations/rat_walk.anim.json
static const AnimKey RAT_WALK_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 75, -2, ANIM_EASE_OUT },
    { 150, 1, ANIM_EASE_IN_OUT },
    { 225, -1, ANIM_EASE_OUT },
    { 300, 0, ANIM_EASE_IN },
};

static const AnimKey RAT_WALK_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 75, 880, ANIM_EASE_OUT },
    { 150, 1160, ANIM_EASE_IN_OUT },
    { 225, 920, ANIM_EASE_OUT },
    { 300, 1000, ANIM_EASE_IN },
};

static const AnimKey RAT_WALK_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 75, 1160, ANIM_EASE_OUT },
    { 150, 860, ANIM_EASE_IN_OUT },
    { 225, 1120, ANIM_EASE_OUT },
    { 300, 1000, ANIM_EASE_IN },
};

static const AnimTrack RAT_WALK_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = RAT_WALK_OFFSET_Y_KEYS,
        .key_count = sizeof(RAT_WALK_OFFSET_Y_KEYS) / sizeof(RAT_WALK_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = RAT_WALK_SCALE_X_KEYS,
        .key_count = sizeof(RAT_WALK_SCALE_X_KEYS) / sizeof(RAT_WALK_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = RAT_WALK_SCALE_Y_KEYS,
        .key_count = sizeof(RAT_WALK_SCALE_Y_KEYS) / sizeof(RAT_WALK_SCALE_Y_KEYS[0]),
    },
};

// Source: src/assets/animations/smash.anim.json
static const AnimKey SMASH_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 50, 4, ANIM_EASE_OUT },
    { 180, 8, ANIM_EASE_LINEAR },
};

static const AnimKey SMASH_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 50, 1240, ANIM_EASE_OUT },
    { 180, 1140, ANIM_EASE_IN },
};

static const AnimKey SMASH_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 50, 780, ANIM_EASE_OUT },
    { 180, 860, ANIM_EASE_IN },
};

static const AnimKey SMASH_ROTATION_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 50, 420, ANIM_EASE_OUT },
    { 180, 420, ANIM_EASE_LINEAR },
};

static const AnimTrack SMASH_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = SMASH_OFFSET_Y_KEYS,
        .key_count = sizeof(SMASH_OFFSET_Y_KEYS) / sizeof(SMASH_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = SMASH_SCALE_X_KEYS,
        .key_count = sizeof(SMASH_SCALE_X_KEYS) / sizeof(SMASH_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = SMASH_SCALE_Y_KEYS,
        .key_count = sizeof(SMASH_SCALE_Y_KEYS) / sizeof(SMASH_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ROTATION,
        .keys = SMASH_ROTATION_KEYS,
        .key_count = sizeof(SMASH_ROTATION_KEYS) / sizeof(SMASH_ROTATION_KEYS[0]),
    },
};

// Source: src/assets/animations/spawn.anim.json
static const AnimKey SPAWN_SCALE_X_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 90, 1220, ANIM_EASE_OUT },
    { 180, 940, ANIM_EASE_IN_OUT },
    { 260, 1000, ANIM_EASE_IN },
};

static const AnimKey SPAWN_SCALE_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 90, 820, ANIM_EASE_OUT },
    { 180, 1080, ANIM_EASE_IN_OUT },
    { 260, 1000, ANIM_EASE_IN },
};

static const AnimKey SPAWN_ALPHA_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 50, 255, ANIM_EASE_OUT },
    { 260, 255, ANIM_EASE_LINEAR },
};

static const AnimTrack SPAWN_TRACKS[] = {
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = SPAWN_SCALE_X_KEYS,
        .key_count = sizeof(SPAWN_SCALE_X_KEYS) / sizeof(SPAWN_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = SPAWN_SCALE_Y_KEYS,
        .key_count = sizeof(SPAWN_SCALE_Y_KEYS) / sizeof(SPAWN_SCALE_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_ALPHA,
        .keys = SPAWN_ALPHA_KEYS,
        .key_count = sizeof(SPAWN_ALPHA_KEYS) / sizeof(SPAWN_ALPHA_KEYS[0]),
    },
};

// Source: src/assets/animations/walk.anim.json
static const AnimKey WALK_OFFSET_Y_KEYS[] = {
    { 0, 0, ANIM_EASE_LINEAR },
    { 120, 2, ANIM_EASE_OUT },
    { 240, -2, ANIM_EASE_IN_OUT },
    { 360, 2, ANIM_EASE_OUT },
    { 480, 0, ANIM_EASE_IN },
};

static const AnimKey WALK_SCALE_X_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 120, 920, ANIM_EASE_OUT },
    { 240, 1120, ANIM_EASE_IN_OUT },
    { 360, 920, ANIM_EASE_OUT },
    { 480, 1000, ANIM_EASE_IN },
};

static const AnimKey WALK_SCALE_Y_KEYS[] = {
    { 0, 1000, ANIM_EASE_LINEAR },
    { 120, 1100, ANIM_EASE_OUT },
    { 240, 900, ANIM_EASE_IN_OUT },
    { 360, 1100, ANIM_EASE_OUT },
    { 480, 1000, ANIM_EASE_IN },
};

static const AnimTrack WALK_TRACKS[] = {
    {
        .property = ANIM_PROP_OFFSET_Y,
        .keys = WALK_OFFSET_Y_KEYS,
        .key_count = sizeof(WALK_OFFSET_Y_KEYS) / sizeof(WALK_OFFSET_Y_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_X,
        .keys = WALK_SCALE_X_KEYS,
        .key_count = sizeof(WALK_SCALE_X_KEYS) / sizeof(WALK_SCALE_X_KEYS[0]),
    },
    {
        .property = ANIM_PROP_SCALE_Y,
        .keys = WALK_SCALE_Y_KEYS,
        .key_count = sizeof(WALK_SCALE_Y_KEYS) / sizeof(WALK_SCALE_Y_KEYS[0]),
    },
};

const AnimationClip ANIMATION_CLIPS[] = {
    {
        .id = "boar_walk",
        .duration_ms = 500,
        .loop = true,
        .tracks = BOAR_WALK_TRACKS,
        .track_count = sizeof(BOAR_WALK_TRACKS) / sizeof(BOAR_WALK_TRACKS[0]),
    },
    {
        .id = "damage",
        .duration_ms = 230,
        .loop = false,
        .tracks = DAMAGE_TRACKS,
        .track_count = sizeof(DAMAGE_TRACKS) / sizeof(DAMAGE_TRACKS[0]),
    },
    {
        .id = "death",
        .duration_ms = 520,
        .loop = false,
        .tracks = DEATH_TRACKS,
        .track_count = sizeof(DEATH_TRACKS) / sizeof(DEATH_TRACKS[0]),
    },
    {
        .id = "fall",
        .duration_ms = 180,
        .loop = false,
        .tracks = FALL_TRACKS,
        .track_count = sizeof(FALL_TRACKS) / sizeof(FALL_TRACKS[0]),
    },
    {
        .id = "fly",
        .duration_ms = 640,
        .loop = true,
        .tracks = FLY_TRACKS,
        .track_count = sizeof(FLY_TRACKS) / sizeof(FLY_TRACKS[0]),
    },
    {
        .id = "flying_death",
        .duration_ms = 520,
        .loop = false,
        .tracks = FLYING_DEATH_TRACKS,
        .track_count = sizeof(FLYING_DEATH_TRACKS) / sizeof(FLYING_DEATH_TRACKS[0]),
    },
    {
        .id = "idle",
        .duration_ms = 720,
        .loop = true,
        .tracks = IDLE_TRACKS,
        .track_count = sizeof(IDLE_TRACKS) / sizeof(IDLE_TRACKS[0]),
    },
    {
        .id = "jump",
        .duration_ms = 280,
        .loop = false,
        .tracks = JUMP_TRACKS,
        .track_count = sizeof(JUMP_TRACKS) / sizeof(JUMP_TRACKS[0]),
    },
    {
        .id = "land",
        .duration_ms = 190,
        .loop = false,
        .tracks = LAND_TRACKS,
        .track_count = sizeof(LAND_TRACKS) / sizeof(LAND_TRACKS[0]),
    },
    {
        .id = "obstacle_break",
        .duration_ms = 260,
        .loop = false,
        .tracks = OBSTACLE_BREAK_TRACKS,
        .track_count = sizeof(OBSTACLE_BREAK_TRACKS) / sizeof(OBSTACLE_BREAK_TRACKS[0]),
    },
    {
        .id = "ork_walk",
        .duration_ms = 720,
        .loop = true,
        .tracks = ORK_WALK_TRACKS,
        .track_count = sizeof(ORK_WALK_TRACKS) / sizeof(ORK_WALK_TRACKS[0]),
    },
    {
        .id = "predator_idle",
        .duration_ms = 960,
        .loop = true,
        .tracks = PREDATOR_IDLE_TRACKS,
        .track_count = sizeof(PREDATOR_IDLE_TRACKS) / sizeof(PREDATOR_IDLE_TRACKS[0]),
    },
    {
        .id = "predator_snap_idle",
        .duration_ms = 720,
        .loop = true,
        .tracks = PREDATOR_SNAP_IDLE_TRACKS,
        .track_count = sizeof(PREDATOR_SNAP_IDLE_TRACKS) / sizeof(PREDATOR_SNAP_IDLE_TRACKS[0]),
    },
    {
        .id = "rat_walk",
        .duration_ms = 300,
        .loop = true,
        .tracks = RAT_WALK_TRACKS,
        .track_count = sizeof(RAT_WALK_TRACKS) / sizeof(RAT_WALK_TRACKS[0]),
    },
    {
        .id = "smash",
        .duration_ms = 180,
        .loop = false,
        .tracks = SMASH_TRACKS,
        .track_count = sizeof(SMASH_TRACKS) / sizeof(SMASH_TRACKS[0]),
    },
    {
        .id = "spawn",
        .duration_ms = 260,
        .loop = false,
        .tracks = SPAWN_TRACKS,
        .track_count = sizeof(SPAWN_TRACKS) / sizeof(SPAWN_TRACKS[0]),
    },
    {
        .id = "walk",
        .duration_ms = 480,
        .loop = true,
        .tracks = WALK_TRACKS,
        .track_count = sizeof(WALK_TRACKS) / sizeof(WALK_TRACKS[0]),
    },
};

const uint8_t ANIMATION_CLIP_COUNT = sizeof(ANIMATION_CLIPS) / sizeof(ANIMATION_CLIPS[0]);
