#ifndef LITTLE_ONE_GENERATED_MUSIC_H
#define LITTLE_ONE_GENERATED_MUSIC_H

#include <stddef.h>
#include <stdint.h>

#include "music_definition.h"

typedef enum {
    MUSIC_ID_NONE = -1,
    MUSIC_ID_AGENT00CAT = 0,
    MUSIC_ID_CARRAMBACAT,
    MUSIC_ID_CATBUSTER,
    MUSIC_ID_DARTHCAT,
    MUSIC_ID_DOOMCAT,
    MUSIC_ID_GAME_OVER,
    MUSIC_ID_HARRYPURRTER,
    MUSIC_ID_IMPAWSIBLECAT,
    MUSIC_ID_INDICAT,
    MUSIC_ID_JAWSCAT,
    MUSIC_ID_MAIN_THEME,
    MUSIC_ID_PINKPAWTHER,
    MUSIC_ID_ROBOCAT,
    MUSIC_ID_ROCKPAW,
    MUSIC_ID_SCARCAT,
    MUSIC_ID_TERMICATOR,
    MUSIC_ID_COUNT
} MusicId;

#define MUSIC_NONE MUSIC_ID_NONE
#define MUSIC_AGENT00CAT MUSIC_ID_AGENT00CAT
#define MUSIC_CARRAMBACAT MUSIC_ID_CARRAMBACAT
#define MUSIC_CATBUSTER MUSIC_ID_CATBUSTER
#define MUSIC_DARTHCAT MUSIC_ID_DARTHCAT
#define MUSIC_DOOMCAT MUSIC_ID_DOOMCAT
#define MUSIC_GAME_OVER MUSIC_ID_GAME_OVER
#define MUSIC_HARRYPURRTER MUSIC_ID_HARRYPURRTER
#define MUSIC_IMPAWSIBLECAT MUSIC_ID_IMPAWSIBLECAT
#define MUSIC_INDICAT MUSIC_ID_INDICAT
#define MUSIC_JAWSCAT MUSIC_ID_JAWSCAT
#define MUSIC_MAIN_THEME MUSIC_ID_MAIN_THEME
#define MUSIC_PINKPAWTHER MUSIC_ID_PINKPAWTHER
#define MUSIC_ROBOCAT MUSIC_ID_ROBOCAT
#define MUSIC_ROCKPAW MUSIC_ID_ROCKPAW
#define MUSIC_SCARCAT MUSIC_ID_SCARCAT
#define MUSIC_TERMICATOR MUSIC_ID_TERMICATOR

typedef struct {
    const char* id;
    int32_t sample_rate;
    int32_t sample_count;
    int32_t loop_enabled;
    int32_t loop_start_sample;
    int32_t loop_end_sample;
    int16_t* samples;
} GeneratedMusic;

extern const PackedMusicDefinition PACKED_MUSIC_DEFINITIONS[];
extern const size_t PACKED_MUSIC_COUNT;

#endif
