// Generated by tools/pack_sfx.py. Do not edit manually.
#include "generated_sound.h"

// Source: src/assets/sfx/jump.sfx.json
static const SoundCommand JUMP_SOUND_COMMANDS[] = {
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 520,
        .frequency_end = 880,
        .duration_ms = 90,
        .volume = 62,
    },
    {
        .wave = SOUND_WAVE_TRIANGLE,
        .frequency_start = 760,
        .frequency_end = 980,
        .duration_ms = 45,
        .volume = 42,
    },
};

// Source: src/assets/sfx/smash.sfx.json
static const SoundCommand SMASH_SOUND_COMMANDS[] = {
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 180,
        .frequency_end = 70,
        .duration_ms = 120,
        .volume = 86,
    },
    {
        .wave = SOUND_WAVE_NOISE,
        .frequency_start = 120,
        .frequency_end = 40,
        .duration_ms = 50,
        .volume = 10,
    },
};

// Source: src/assets/sfx/damage.sfx.json
static const SoundCommand DAMAGE_SOUND_COMMANDS[] = {
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 920,
        .frequency_end = 540,
        .duration_ms = 55,
        .volume = 74,
    },
    {
        .wave = SOUND_WAVE_NOISE,
        .frequency_start = 300,
        .frequency_end = 120,
        .duration_ms = 45,
        .volume = 48,
    },
};

// Source: src/assets/sfx/death.sfx.json
static const SoundCommand DEATH_SOUND_COMMANDS[] = {
    {
        .wave = SOUND_WAVE_TRIANGLE,
        .frequency_start = 520,
        .frequency_end = 180,
        .duration_ms = 180,
        .volume = 76,
    },
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 220,
        .frequency_end = 80,
        .duration_ms = 120,
        .volume = 54,
    },
};

// Source: src/assets/sfx/ork_death.sfx.json
static const SoundCommand ORK_DEATH_SOUND_COMMANDS[] = {
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 160,
        .frequency_end = 55,
        .duration_ms = 260,
        .volume = 88,
    },
    {
        .wave = SOUND_WAVE_TRIANGLE,
        .frequency_start = 110,
        .frequency_end = 45,
        .duration_ms = 220,
        .volume = 76,
    },
    {
        .wave = SOUND_WAVE_NOISE,
        .frequency_start = 80,
        .frequency_end = 25,
        .duration_ms = 160,
        .volume = 58,
    },
};

// Source: src/assets/sfx/boar_death.sfx.json
static const SoundCommand BOAR_DEATH_SOUND_COMMANDS[] = {
    {
        .wave = SOUND_WAVE_TRIANGLE,
        .frequency_start = 260,
        .frequency_end = 95,
        .duration_ms = 210,
        .volume = 82,
    },
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 140,
        .frequency_end = 60,
        .duration_ms = 170,
        .volume = 70,
    },
};

// Source: src/assets/sfx/rat_death.sfx.json
static const SoundCommand RAT_DEATH_SOUND_COMMANDS[] = {
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 1180,
        .frequency_end = 760,
        .duration_ms = 45,
        .volume = 70,
    },
    {
        .wave = SOUND_WAVE_SQUARE,
        .frequency_start = 880,
        .frequency_end = 1320,
        .duration_ms = 35,
        .volume = 58,
    },
    {
        .wave = SOUND_WAVE_NOISE,
        .frequency_start = 420,
        .frequency_end = 160,
        .duration_ms = 35,
        .volume = 32,
    },
};

const SoundDefinition PACKED_SOUND_DEFINITIONS[] = {
    {
        .id = "jump",
        .commands = JUMP_SOUND_COMMANDS,
        .command_count = sizeof(JUMP_SOUND_COMMANDS) / sizeof(JUMP_SOUND_COMMANDS[0]),
    },
    {
        .id = "smash",
        .commands = SMASH_SOUND_COMMANDS,
        .command_count = sizeof(SMASH_SOUND_COMMANDS) / sizeof(SMASH_SOUND_COMMANDS[0]),
    },
    {
        .id = "damage",
        .commands = DAMAGE_SOUND_COMMANDS,
        .command_count = sizeof(DAMAGE_SOUND_COMMANDS) / sizeof(DAMAGE_SOUND_COMMANDS[0]),
    },
    {
        .id = "death",
        .commands = DEATH_SOUND_COMMANDS,
        .command_count = sizeof(DEATH_SOUND_COMMANDS) / sizeof(DEATH_SOUND_COMMANDS[0]),
    },
    {
        .id = "ork_death",
        .commands = ORK_DEATH_SOUND_COMMANDS,
        .command_count = sizeof(ORK_DEATH_SOUND_COMMANDS) / sizeof(ORK_DEATH_SOUND_COMMANDS[0]),
    },
    {
        .id = "boar_death",
        .commands = BOAR_DEATH_SOUND_COMMANDS,
        .command_count = sizeof(BOAR_DEATH_SOUND_COMMANDS) / sizeof(BOAR_DEATH_SOUND_COMMANDS[0]),
    },
    {
        .id = "rat_death",
        .commands = RAT_DEATH_SOUND_COMMANDS,
        .command_count = sizeof(RAT_DEATH_SOUND_COMMANDS) / sizeof(RAT_DEATH_SOUND_COMMANDS[0]),
    },
};

const size_t PACKED_SOUND_COUNT = sizeof(PACKED_SOUND_DEFINITIONS) / sizeof(PACKED_SOUND_DEFINITIONS[0]);
