#ifndef LITTLE_ONE_LOCALIZATION_H
#define LITTLE_ONE_LOCALIZATION_H

#include "../settings/game_settings.h"

typedef enum {
    LOCALIZED_TEXT_BACK = 0,
    LOCALIZED_TEXT_BEST,
    LOCALIZED_TEXT_CHANGE_CAT,
    LOCALIZED_TEXT_CHOOSE_CAT,
    LOCALIZED_TEXT_CONGRATULATIONS,
    LOCALIZED_TEXT_CONTINUE,
    LOCALIZED_TEXT_GAME_OVER,
    LOCALIZED_TEXT_EXIT,
    LOCALIZED_TEXT_LANGUAGE,
    LOCALIZED_TEXT_LANGUAGE_ENGLISH,
    LOCALIZED_TEXT_LANGUAGE_UKRAINIAN,
    LOCALIZED_TEXT_LOCK,
    LOCALIZED_TEXT_LOCKED,
    LOCALIZED_TEXT_MUSIC,
    LOCALIZED_TEXT_ALL_CATS_READY,
    LOCALIZED_TEXT_PAUSED,
    LOCALIZED_TEXT_RESUME,
    LOCALIZED_TEXT_RETRY,
    LOCALIZED_TEXT_RUNS,
    LOCALIZED_TEXT_SCORE,
    LOCALIZED_TEXT_SETTINGS,
    LOCALIZED_TEXT_SFX,
    LOCALIZED_TEXT_START,
    LOCALIZED_TEXT_TIME,
    LOCALIZED_TEXT_TOTAL,
    LOCALIZED_TEXT_CAT_AGENT00CAT_NAME,
    LOCALIZED_TEXT_CAT_CARRAMBACAT_NAME,
    LOCALIZED_TEXT_CAT_CATBUSTER_NAME,
    LOCALIZED_TEXT_CAT_DARTHCAT_NAME,
    LOCALIZED_TEXT_CAT_DOOMCAT_NAME,
    LOCALIZED_TEXT_CAT_HARRYPURRTER_NAME,
    LOCALIZED_TEXT_CAT_IMPAWSIBLECAT_NAME,
    LOCALIZED_TEXT_CAT_INDICAT_NAME,
    LOCALIZED_TEXT_CAT_JAWSCAT_NAME,
    LOCALIZED_TEXT_CAT_PINKPAWTHER_NAME,
    LOCALIZED_TEXT_CAT_ROBOCAT_NAME,
    LOCALIZED_TEXT_CAT_ROCKPAW_NAME,
    LOCALIZED_TEXT_CAT_SCARCAT_NAME,
    LOCALIZED_TEXT_CAT_TERMICATOR_NAME,
    LOCALIZED_TEXT_CAT_AGENT00CAT_INTRO,
    LOCALIZED_TEXT_CAT_CARRAMBACAT_INTRO,
    LOCALIZED_TEXT_CAT_CATBUSTER_INTRO,
    LOCALIZED_TEXT_CAT_DARTHCAT_INTRO,
    LOCALIZED_TEXT_CAT_DOOMCAT_INTRO,
    LOCALIZED_TEXT_CAT_HARRYPURRTER_INTRO,
    LOCALIZED_TEXT_CAT_IMPAWSIBLECAT_INTRO,
    LOCALIZED_TEXT_CAT_INDICAT_INTRO,
    LOCALIZED_TEXT_CAT_JAWSCAT_INTRO,
    LOCALIZED_TEXT_CAT_PINKPAWTHER_INTRO,
    LOCALIZED_TEXT_CAT_ROBOCAT_INTRO,
    LOCALIZED_TEXT_CAT_ROCKPAW_INTRO,
    LOCALIZED_TEXT_CAT_SCARCAT_INTRO,
    LOCALIZED_TEXT_CAT_TERMICATOR_INTRO
} LocalizedTextId;

const char* localization_text(GameLocale locale, LocalizedTextId text_id);

#endif
