#ifndef LITTLE_ONE_LOCALIZATION_H
#define LITTLE_ONE_LOCALIZATION_H

#include "../settings/game_settings.h"

typedef enum {
    LOCALIZED_TEXT_BACK = 0,
    LOCALIZED_TEXT_BEST,
    LOCALIZED_TEXT_GAME_OVER,
    LOCALIZED_TEXT_EXIT,
    LOCALIZED_TEXT_LANGUAGE,
    LOCALIZED_TEXT_LANGUAGE_ENGLISH,
    LOCALIZED_TEXT_LANGUAGE_UKRAINIAN,
    LOCALIZED_TEXT_MUSIC,
    LOCALIZED_TEXT_NEW_RECORD,
    LOCALIZED_TEXT_PAUSED,
    LOCALIZED_TEXT_RESUME,
    LOCALIZED_TEXT_RETRY,
    LOCALIZED_TEXT_RUNS,
    LOCALIZED_TEXT_SCORE,
    LOCALIZED_TEXT_SETTINGS,
    LOCALIZED_TEXT_SFX,
    LOCALIZED_TEXT_START,
    LOCALIZED_TEXT_TIME,
    LOCALIZED_TEXT_TOTAL
} LocalizedTextId;

const char* localization_text(GameLocale locale, LocalizedTextId text_id);

#endif
